export const createInitialTables: string[] =
  // [
  //   `DROP TABLE workouts;`,
  //   `DROP TABLE days_to_workouts;`,
  //   `DROP TABLE workout_data;`,
  // ];
  [
    `PRAGMA foreign_keys = ON;`,
    `CREATE TABLE IF NOT EXISTS days (NAME TEXT NOT NULL PRIMARY KEY);`,
    `CREATE TABLE IF NOT EXISTS workouts(ID INTEGER PRIMARY KEY AUTOINCREMENT, NAME TEXT NOT NULL UNIQUE, REPS TEXT NOT NULL, NOTES TEXT, LINK TEXT, TYPE TEXT NOT NULL);`,
    `CREATE TABLE IF NOT EXISTS days_to_workouts (ID INTEGER PRIMARY KEY AUTOINCREMENT, DAYS TEXT NOT NULL, WORKOUTS INTEGER NOT NULL,
 UNIQUE(DAYS, WORKOUTS),
FOREIGN KEY (DAYS) REFERENCES days (NAME) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(WORKOUTS) REFERENCES workouts (ID) ON DELETE CASCADE ON UPDATE CASCADE);`,
    `CREATE TABLE IF NOT EXISTS workout_data (ID INTEGER PRIMARY KEY AUTOINCREMENT, WORKOUT INTEGER NOT NULL, DATE TEXT NOT NULL, VALUE INT NOT NULL,
    FOREIGN KEY (WORKOUT) REFERENCES workouts (ID) ON DELETE CASCADE ON UPDATE CASCADE);`,
  ];
// TODO: modify sql to add unique constraint on workout names
